### ISSUE TITLE
404 on https://dospolov.com/tag/account-surfer/

### ISSUE THREAD

**Issue by muescha** [dospolov/gatsby-starter-blog-and-cv#2]
404 https://dospolov.com/tag/account-surfer/

**Comment by dospolov** [comment]
@muescha not sure why you are getting 404:
![image](https://user-images.githubusercontent.com/670682/75428579-194e3400-5951-11ea-9903-796c34d37a4b.png)

**Comment by dospolov** [comment]
@muescha could you please check now?

**Comment by muescha** [comment]
now it is ok :)
