### ISSUE TITLE
What is the correct way to add new Categories & Tags?

### ISSUE THREAD

**Issue by cmarabate** [dospolov/gatsby-starter-blog-and-cv#3]
Hello, I deployed this to Netlify and setup Netlify Identity to login to the backend and edited a post. I simply changed its category to one that didn't already exist and I added a new tag that didn't already exist.

I think the tag might have got added correctly but the category doesn't seem right. 

It doesn't look like a new color gets generated for the new category like I was hoping and when it takes me to a blank page when I click on it.

You can view the live site I'm referring to here...
[https://gatsby-starter-blog-and-cv.cmarabate.com/](https://gatsby-starter-blog-and-cv.cmarabate.com/)

"NewCategory" and "newtag" were what I added to the "Trello + GTD = Trello Bookmark" post.

I had Netlify clear the cache and redeploy afterward even though I don't think I should have to do that because Netlify automatically rebuilds after publishing changes. 

Did I do something wrong or is there something I am missing? Do I have to create new files somewhere in the src folder or edit the ones already there when I need to add a new category?

Thanks,

Chris

**Comment by dospolov** [comment]
hi @cmarabate 
thanks for reaching me. Yeap, that's a bug. Working on that

**Comment by dospolov** [comment]
@cmarabate please check updated version

**Comment by cmarabate** [comment]
It works beautifully now, great work!

[https://gatsby-starter-blog-and-cv.cmarabate.com/category/newcat](https://gatsby-starter-blog-and-cv.cmarabate.com/category/newcat)
[https://gatsby-starter-blog-and-cv.cmarabate.com/tag/newtag](https://gatsby-starter-blog-and-cv.cmarabate.com/tag/newtag)

Thanks,

Chris
