### ISSUE TITLE
Remove skills value

### ISSUE THREAD

**Issue by a-vasylieva** [dospolov/gatsby-starter-blog-and-cv#5]
![image](https://user-images.githubusercontent.com/46456902/78685704-ccb82a00-78fa-11ea-9200-6b8c9972ce54.png)

**Comment by dospolov** [comment]
Fixed in: https://github.com/dospolov/gatsby-starter-blog-and-cv/commit/2a5d4a65c9e355fb7d228a41d9364789d01fcd38
