### ISSUE TITLE
Unable to find license for this starter

### ISSUE THREAD

**Issue by trevorlazarus** [dospolov/gatsby-starter-blog-and-cv#9]
Thank you so much for sharing this project. I'm new to Gatsby and Tailwind and finding this starter super useful to learn both.

I was looking around to find a license within this repo, but am unable to do so. 

I'm interested in using this starter for my personal blog and would like to make sure that it's got the correct license and it's okay for me to use it.

**Comment by trevorlazarus** [comment]
There's a mention of license within the package.json file:
![image](https://user-images.githubusercontent.com/3745470/103067486-e85f7f80-45b2-11eb-98e3-f78e5b3b0b44.png)

Am I correct to assume that this is MIT licensed? Thanks.

**Comment by dospolov** [comment]
Thanks for feedback.
Sure you can use it for your needs - this is why I shared this starter :)

**Comment by trevorlazarus** [comment]
Okay, thanks.
